### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by suvanbanerjee** [asakura42/btstrm#3]
Its better to have a requirements.txt file in project it makes it easy to install dependencies 
thus you can replace 

`pip install requests tqdm colorama beautifulsoup4 unidecode`   by  `pip install -r requirements.txt`

**Comment by asakura42** [comment]
You can easily install `btstrm` with `pip` or `pipx`: `pipx install btstrm`.
But if you need to install it from local directory, you can run `python -m pip install .`
I don't think this project needs `requirements.txt` while `pyproject.toml` exist but I fixed README in https://github.com/asakura42/btstrm/commit/e9c7d63da7a0fbfe56933e23a4db3d6aa4098a22
